version: 1
global:
  no_markdown_html:
    points: 0.0        # критический критерий: при нарушении ответ невалиден/сильный штраф
    critical: true
  formatting_headers:
    points: 1.0        # корректные эмодзи-заголовки/структура в целом
  tone_professional:
    points: 1.0        # деловой тон, отсутствие эйфорики и "воды"
  news_2_2_2:
    points: 1.5        # правило 2 политика + 2 экономика + 2 рынок (только для опций с новостями)
profiles:

  zodiac_info:
    min_words_per_section: 75
    sections:
      - id: zodiac_desc
        title: "🌟 ОПИСАНИЕ ЗНАКА ЗОДИАКА"
        presence: 0.5
        quality: 0.5
      - id: numerology
        title: "🔢 НУМЕРОЛОГИЯ КОМПАНИИ"
        presence: 0.5
        quality: 0.5
      - id: examples
        title: "🏢 ПРИМЕРЫ КОМПАНИЙ"
        presence: 0.5
        quality: 0.5
    extra:
      known_companies: 0.5   # есть 2–3 релевантных примера из справочника

  business_forecast:
    min_words_per_section: 75
    sections:
      - { id: zodiac_short,     title: "🌟 ОПИСАНИЕ ЗНАКА ЗОДИАКА", presence: 0.5, quality: 0.5 }
      - { id: planetary_geo,    title: "🔮 ПЛАНЕТАРНОЕ ВЛИЯНИЕ",   presence: 0.5, quality: 0.5 }
      - { id: news_actions,     title: "💼 НОВОСТНАЯ ПОВЕСТКА И РЕКОМЕНДАЦИИ", presence: 0.5, quality: 0.5 }
      - { id: owners_directors, title: "🌟 ВЛИЯНИЕ СОБСТВЕННИКА И ДИРЕКТОРА НА БИЗНЕС", presence: 0.5, quality: 0.5 }
      - { id: conclusion,       title: "ЗАКЛЮЧЕНИЕ", presence: 0.5, quality: 0.5 }
    extra:
      news_2_2_2: 1.5
      industry_binding: 1.0      # учтена отрасль в рекомендациях

  compatibility:
    min_words_per_section: 75
    sections:
      - { id: astro_compat,   title: "🔮 АСТРОЛОГИЧЕСКАЯ СОВМЕСТИМОСТЬ", presence: 0.5, quality: 0.5 }
      - { id: num_compat,     title: "🔢 НУМЕРОЛОГИЧЕСКАЯ СОВМЕСТИМОСТЬ", presence: 0.5, quality: 0.5 }
      - { id: news_context,   title: "📰 АКТУАЛЬНЫЕ НОВОСТИ И КОНТЕКСТ", presence: 0.5, quality: 0.5 }
      - { id: recommendations, title: "💼 ПРАКТИЧЕСКИЕ РЕКОМЕНДАЦИИ", presence: 0.5, quality: 0.5 }
    extra:
      status_binding: 1.0        # учтён статус (сотрудник/партнёр/контрагент)

  daily_forecast:
    min_words_per_section: 75
    sections:
      - { id: general,         title: "🌟 ОБЩИЙ АСТРОЛОГИЧЕСКИЙ ФОН", presence: 0.5, quality: 0.5 }
      - { id: detailed,        title: "🔮 ДЕТАЛЬНЫЙ ПРОГНОЗ", presence: 0.5, quality: 0.5 }
      - { id: numerology,      title: "🔢 НУМЕРОЛОГИЧЕСКОЕ ВЛИЯНИЕ", presence: 0.5, quality: 0.5 }
      - { id: news_context,    title: "📰 АКТУАЛЬНЫЕ НОВОСТИ И КОНТЕКСТ", presence: 0.5, quality: 0.5 }
      - { id: recommendations, title: "💼 ПРАКТИЧЕСКИЕ РЕКОМЕНДАЦИИ", presence: 0.5, quality: 0.5 }
    extra:
      news_2_2_2: 1.5
      industry_binding: 1.0
